/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mperry' at '8/08/14 3:51 PM' with Gradle 2.0
 *
 * @author mperry, @date 8/08/14 3:51 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
