/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mperry' at '8/08/14 3:51 PM' with Gradle 2.0
 *
 * @author mperry, @date 8/08/14 3:51 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
